### ISSUE TITLE
Create main page

### ISSUE THREAD

**Issue by xansochi** [skbu3u/web-interface#5]
**Create main page**

After successful login user redirected to this main page.

Main page include global dashboard,user information block with logout function,and other additional functions. The design of the page, the layout of the components and the interface are simple for tests and a preview.

**Comment by Lehersun** [comment]
Let's start from a design part. It would good to see how it is looking. The best solution for it, at this moment, is a FIgma. It can provide us a possibility of team work with design, fast review and UX side understanding
